spring.application.name=ticket-master-backend
# CONFIGURAÇÃO DE CONEXÃO COM O ORACLE (DOCKER)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=SYSTEM
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# CONFIGURAÇÕES DO HIBERNATE / JPA
# O dialeto correto para a versão 21c do Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Mostra as queries SQL que o Spring executar no console (ótimo para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## Estratégia de criação do banco: 'update' cria/altera as tabelas automaticamente com base nas suas entidades Java
#spring.jpa.hibernate.ddl-auto=update

# ===============================
# CONFIGURAÇÃO DO KAFKA (PRODUCER)
# ===============================
# Indica onde o servidor do Kafka está rodando
spring.kafka.bootstrap-servers=localhost:9092

# Define como o Spring vai transformar as chaves e os valores dos objetos em texto/bytes para trafegar na rede
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer